# Generated by Django 6.0.3 on 2026-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
