# Generated by Django 6.0.3 on 2026-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0002_alter_comment_date_added_alter_reply_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="text",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
