# Generated by Django 6.0.3 on 2026-03-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0004_comment_owner_reply_owner_thread_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="thread",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
